services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db # Persist data

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port
    volumes:
      - redis_data:/data # Persist data

  # FAISS Vector Search Service
  faiss:
    image: python:3.12-slim
    container_name: faiss
    volumes:
      - faiss_data:/app/faiss_indexes
      - ./faiss_service:/app
    working_dir: /app
    command: >
      bash -c "pip install faiss-cpu fastapi uvicorn numpy && 
              uvicorn faiss_service:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001" # Expose FAISS service port

  # Backend Service (FastAPI)
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Bind mount for live reload
    depends_on:
      - mongodb
      - redis
      - faiss
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017"
      REDIS_URI: "redis://redis:6379"
      FAISS_SERVICE_URL: "http://faiss:8001"

# Volumes for data persistence
volumes:
  mongodb_data:
  redis_data:
  faiss_data: